#!/usr/bin/env python3
"""Generate the wordmark SVGs: solid word, with the proof set beneath it.

    python tools/make_wordmark.py

Writes assets/oblivio-wordmark-mono.svg (black, light ground) and
assets/oblivio-wordmark-mono-inverse.svg (white, dark ground).

Why a generator rather than two hand-written files
--------------------------------------------------
The two differ only in ink. Hand-maintaining both guarantees they drift, and a
mark that renders differently on GitHub's two themes is worse than one that only
works on one -- at least the second failure is visible to its author.

Why the proof is under the word and not inside it
-------------------------------------------------
An earlier version clipped the hex into the letterforms. It looked like texture
rather than evidence: at README width the digits were far too small to make out,
so the mark displayed a proof nobody could actually check. A mark that shows an
unreadable proof is decoration claiming to be a guarantee. Solid word, legible
root underneath.

The root is real: the one the README's succinct-membership demo prints. Checkable
against a published value rather than hex chosen to look cryptographic.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The root printed by the succinct-membership demo in README.md.
MERKLE_ROOT = "1d5e3e4a5fb29328"

W, H = 340, 96
ANCHOR_X = 173.25      # 340/2 + half the letter-spacing; see the SVG comment
BASELINE = 58
FONT_SIZE = 40
TRACKING = 6.5
STACK = ("ui-sans-serif, -apple-system, 'Segoe UI', Roboto, "
         "Helvetica, Arial, sans-serif")

# The proof line. Sized to be read, not to be decorative.
PROOF_SIZE = 9
PROOF_TRACKING = 2.6
PROOF_BASELINE = 78
PROOF_OPACITY = 0.68   # secondary to the word, still plainly legible
PROOF_STACK = ("ui-monospace, SFMono-Regular, Consolas, "
               "'Liberation Mono', monospace")


def svg(ink: str, ground: str) -> str:
    # NB: no "--" anywhere in the comment below. XML forbids it inside a comment,
    # and GitHub renders README SVGs through a sanitiser that drops the file
    # rather than repairing it, so the mark would simply not appear.
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}"
     role="img" aria-label="Oblivio">
  <title>Oblivio</title>
  <!-- GENERATED by tools/make_wordmark.py. Edit that, not this.

       Solid {ink} wordmark on a {ground} ground, with the proof beneath it:
       {MERKLE_ROOT} is the Merkle root the README's membership demo prints. Real,
       published, checkable, rather than hex chosen to look cryptographic.

       An earlier version clipped the hex into the letterforms. It read as texture
       instead of evidence, because at README width the digits were far too small
       to make out, and a mark showing an unreadable proof is decoration claiming
       to be a guarantee. Solid word, legible root.

       The pair is switched by prefers-color-scheme in the README: a single-ink
       mark needs both inks, or half the readers get nothing.

       The wordmark is live <text>. Convert to outlines before print, embroidery,
       or handing this to anyone whose renderer you do not control.

       Centred with text-anchor rather than a computed x: the stack resolves
       differently per platform and a measured offset is only centred on the
       machine that measured it. x is {ANCHOR_X} rather than {W // 2} because SVG
       adds the tracking after the final glyph too, so the advance being centred
       is {TRACKING}px wider than the ink. The proof line is nudged the same way
       for its own tracking. -->
  <text x="{ANCHOR_X}" y="{BASELINE}" text-anchor="middle"
        font-family="{STACK}"
        font-size="{FONT_SIZE}" letter-spacing="{TRACKING}"
        fill="{ink}" font-weight="700">OBLIVIO</text>
  <text x="{W / 2 + PROOF_TRACKING / 2}" y="{PROOF_BASELINE}" text-anchor="middle"
        font-family="{PROOF_STACK}"
        font-size="{PROOF_SIZE}" letter-spacing="{PROOF_TRACKING}"
        fill="{ink}" opacity="{PROOF_OPACITY}">{MERKLE_ROOT}</text>
</svg>
"""


def main() -> int:
    targets = [
        ("assets/oblivio-wordmark-mono.svg", "#000000", "light"),
        ("assets/oblivio-wordmark-mono-inverse.svg", "#FFFFFF", "dark"),
    ]
    for rel, ink, ground in targets:
        (ROOT / rel).write_text(svg(ink, ground), encoding="utf-8")
        print(f"wrote {rel}  (solid {ink} on {ground}, proof {MERKLE_ROOT})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
